<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--   <xacro:include filename="$(find h1_description)/xacro/transmission.xacro"/>   --> 
    
    <xacro:macro name = "left_arm"> 

        <joint name="arm_l1_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0.02 0.255 0.170"/> 
            <parent link="base_link"/>
            <child link="arm_l1_link"/>
            <axis xyz="0 1 0"/>       
            <dynamics damping="${damping}" friction="${friction}"/> 
            <limit effort="${arm_link1_torque_max}" velocity="${arm_link1_velocity_max}" lower="${arm_link1_min}"   
                       upper="${arm_link1_max}"/>    
        </joint>

        <link name="arm_l1_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://h1_description/meshes/stl/arm_l1_link.STL"
                          scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>
            <collision>
            <!--   <origin rpy="${pi/2.0} 0 0" xyz="0 0 0"/>   --> 
            <origin rpy="0 ${pi/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${arm_l1_link_length * 0.5}" radius="${arm_l1_link_radius * 0.9}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${arm_l1_link_com_x} ${arm_l1_link_com_y} ${arm_l1_link_com_z}"/>  
                <mass value="${arm_l1_link_mass}"/>
                <inertia
                        ixx="${arm_l1_link_ixx}" ixy="${arm_l1_link_ixy}" ixz="${arm_l1_link_ixz}"
                        iyy="${arm_l1_link_iyy}" iyz="${arm_l1_link_iyz}"
                        izz="${arm_l1_link_izz}"/>
            </inertial>
        </link>

        <joint name="arm_l2_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="arm_l1_link"/>
            <child link="arm_l2_link"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
                <limit effort="${arm_link2_torque_max}" velocity="${arm_link2_velocity_max}" lower="${arm_l2_link_min}"
                   upper="${arm_l2_link_max}"/>
        </joint>

        <link name="arm_l2_link">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>   
                <geometry>
                        <mesh filename="package://h1_description/meshes/stl/arm_l2_link.STL"
                              scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>
            <collision> 
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-arm_l2_link_length/2.0 - arm_l1_link_radius}"/>
                <geometry>
                    <box size="${arm_l2_link_length} ${arm_l2_link_width * 0.8} ${arm_l2_link_height * 0.8}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${arm_l2_link_com_x} ${arm_l2_link_com_y} ${arm_l2_link_com_z}"/>
                <mass value="${arm_l2_link_mass}"/>
                <inertia
                        ixx="${arm_l2_link_ixx}" ixy="${arm_l2_link_ixy}" ixz="${arm_l2_link_ixz}"
                        iyy="${arm_l2_link_iyy}" iyz="${arm_l2_link_iyz}"
                        izz="${arm_l2_link_izz}"/>
            </inertial>
        </link>

        <joint name="arm_l3_joint" type="fixed">
        <!--   <origin rpy="0 0 0" xyz="0 0 ${-arm_l2_link_length}"/>    --> 
        <!--    <origin rpy="0 0 0" xyz="0.04 -0.007 -0.2958"/>  --> 
        <origin rpy="0 0 0" xyz="0.022 -0.007 -0.30"/>
            <parent link="arm_l2_link"/>
            <child link="arm_l3_link"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${arm_link3_torque_max}" velocity="${arm_link3_velocity_max}" lower="${arm_link3_min}"
                       upper="${arm_link3_max}"/>
        </joint>

        <link name="arm_l3_link">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://h1_description/meshes/stl/arm_l3_link.STL"
                          scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>
            <collision>
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-arm_l3_link_length/2.0}"/>
                <geometry>
                    <box size="${arm_l3_link_length * 0.8} ${arm_l3_link_width * 0.6} ${arm_l3_link_height * 0.6}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${arm_l3_link_com_x} ${arm_l3_link_com_y} ${arm_l3_link_com_z}"/>
                <mass value="${arm_l3_link_mass}"/>
                <inertia
                        ixx="${arm_l3_link_ixx}" ixy="${arm_l3_link_ixy}" ixz="${arm_l3_link_ixz}"
                        iyy="${arm_l3_link_iyy}" iyz="${arm_l3_link_iyz}"
                        izz="${arm_l3_link_izz}"/>
            </inertial>
        </link>
    </xacro:macro>
</robot>
