<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find h1_description)/xacro/transmission.xacro"/>

    <xacro:macro name="right_arm"> 

        <joint name="arm_r1_joint" type="fixed">
       <origin rpy="0 0 0" xyz="0.02 -0.255 0.170"/> 
            <parent link="base_link"/>
            <child link="arm_r1_link"/>
            <axis xyz="0 1 0"/>       
            <dynamics damping="${damping}" friction="${friction}"/> 
            <limit effort="${arm_link1_torque_max}" velocity="${arm_link1_velocity_max}" lower="${arm_link1_min}"   
                       upper="${arm_link1_max}"/>    
        </joint>

        <link name="arm_r1_link">
            <visual>
             <origin rpy="0 0 0" xyz="0 0 0"/>  
                <geometry>
                    <mesh filename="package://h1_description/meshes/stl/arm_r1_link.STL"
                          scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>
            <collision>
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder length="${arm_r1_link_length * 0.5}" radius="${arm_r1_link_radius * 0.9}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${arm_r1_link_com_x} ${arm_r1_link_com_y} ${arm_r1_link_com_z}"/>  
                <mass value="${arm_r1_link_mass}"/>
                <inertia
                        ixx="${arm_r1_link_ixx}" ixy="${arm_r1_link_ixy}" ixz="${arm_r1_link_ixz}"
                        iyy="${arm_r1_link_iyy}" iyz="${arm_r1_link_iyz}"
                        izz="${arm_r1_link_izz}"/>
            </inertial>
        </link>

        <joint name="arm_r2_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="arm_r1_link"/>
            <child link="arm_r2_link"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
                <limit effort="${arm_link2_torque_max}" velocity="${arm_link2_velocity_max}" lower="${arm_r2_link_min}"
                   upper="${arm_r2_link_max}"/>
        </joint>

        <link name="arm_r2_link">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>   
                <geometry>
                        <mesh filename="package://h1_description/meshes/stl/arm_r2_link.STL"
                              scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>

            <collision> 
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-arm_r2_link_length/2.0 - arm_r1_link_radius}"/>
                <geometry>
                    <box size="${arm_r2_link_length} ${arm_r2_link_width * 0.8} ${arm_r2_link_height * 0.8}"/>
                </geometry>
            </collision>

            <inertial>
                <origin rpy="0 0 0" xyz="${arm_r2_link_com_x} ${arm_r2_link_com_y} ${arm_r2_link_com_z}"/>
                <mass value="${arm_r2_link_mass}"/>
                <inertia
                        ixx="${arm_r2_link_ixx}" ixy="${arm_r2_link_ixy}" ixz="${arm_r2_link_ixz}"
                        iyy="${arm_r2_link_iyy}" iyz="${arm_r2_link_iyz}"
                        izz="${arm_r2_link_izz}"/>
            </inertial>
        </link>

        <joint name="arm_r3_joint" type="fixed">
         <!--    <origin rpy="0 0 0" xyz="0 0 ${-arm_r2_link_length}"/>   --> 
         <!--   <origin rpy="0 0 0" xyz="0.04 -0.007 -0.2958"/>   --> 
            <origin rpy="0 0 0" xyz="0.022 -0.007 -0.30"/>
            <parent link="arm_r2_link"/>
            <child link="arm_r3_link"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${arm_link3_torque_max}" velocity="${arm_link3_velocity_max}" lower="${arm_link3_min}"
                       upper="${arm_link3_max}"/>
        </joint>

        <link name="arm_r3_link">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://h1_description/meshes/stl/arm_r3_link.STL"
                          scale="1 1 1"/>
                </geometry>
                <material name="brown"/>
            </visual>
            <collision>
                <origin rpy="0 ${pi/2.0} 0" xyz="0 0 ${-arm_r3_link_length/2.0}"/>
                <geometry>
                    <box size="${arm_r3_link_length * 0.8} ${arm_r3_link_width * 0.6} ${arm_r3_link_height * 0.6}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${arm_r3_link_com_x} ${arm_r3_link_com_y} ${arm_r3_link_com_z}"/>
                <mass value="${arm_r3_link_mass}"/>
                <inertia
                        ixx="${arm_r3_link_ixx}" ixy="${arm_r3_link_ixy}" ixz="${arm_r3_link_ixz}"
                        iyy="${arm_r3_link_iyy}" iyz="${arm_r3_link_iyz}"
                        izz="${arm_r3_link_izz}"/>
            </inertial>
        </link>
    </xacro:macro>
</robot>
